### ISSUE TITLE
The driver would suddenly fatally exit after ten or more hours.

### ISSUE THREAD

**Issue by hbgxsm95** [d2r2/go-dht#10]
Hi. I tried to use the driver to detect the temperature in the indoor environment for days.  However, it would always suddenly throw a fatal message after collecting the temperature data for ten or more hours.   Is there anyway for ignoring this kind of outlier?

**Comment by d2r2** [comment]
@hbgxsm95, did you finally found the root cause of this issue?

**Comment by hbgxsm95** [comment]
Nope.  I set the retry times as 10. Maybe because this number is too small. I set it as 50 and after half days, everything still goes normal.

**Comment by d2r2** [comment]
Right, reading this sequential bits with milliseconds in between in Linux user space is not precise in regards of time periods, so relatively small retry count could exhaust. Please, let me know in some later time about stability of sensor reading :)

**Comment by hbgxsm95** [comment]
Sure I would love to.

**Comment by d2r2** [comment]
Hi @hbgxsm95. It seems I found and fixed root cause of issue, that lead to fatal exit after long application run. Issue described in #13 and fixed in #14 (fix already merged to master).
Sorry for missing this from the beginning, I hope it will be useful for you. Thanks!
