### ISSUE TITLE
Code fails on RPI-Zero but not on RPI-3

### ISSUE THREAD

**Issue by mmussett** [d2r2/go-dht#12]
Hi,

Tested on RPI 3B+, tried running on RPI-Zero and it fails with the following error:

Error during call C.dial_DHTxx_and_read(): failed to export pin 4

Any help much appreciated.

**Comment by d2r2** [comment]
Hi @mmussett! Sorry for late responce. Main assumption - hardware pin used to attach Sensor data wire, doesn't match pin 4.

You should verify this using such pinout schemes: [https://raspberrypi.stackexchange.com/questions/83610/gpio-pinout-orientation-raspberypi-zero-w](url)
